### ISSUE TITLE
Line terminators: yay or nay?

### ISSUE THREAD

**Issue by jwpjrdev** [jwpjrdev/lem-lang#9]
Should we have line terminators (e.g. semicolons at the end of lines)?
Currently, it's simpler to implement line terminators, but it would be preferred to remove them altogether.

**Comment by IkeVoodoo** [comment]
Yay

**Comment by jwpjrdev** [comment]
I've decided that since the primary target audience is for those who want to write readable, maintainable scripts, there will be no line terminators. New statements will need to be on a new line.
